TelefonDefteri.Web/Controllers/CallLogController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TelefonDefteriService;

namespace TelefonDefteri.Web.Controllers
{
    public class CallLogController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            var userId = (int)HttpContext.Session.GetInt32("user_userId");

            CallLogService servis = new();
            var result = servis.CallLogListPeople(userId);
            return View(result);
        }

        [HttpPost]
        public IActionResult GetCallListDetail(int listId)
        {
            CallLogService servis = new();
            var result = servis.GetCallListDetail(listId);
            return Json(result);
        }

    }
}

TelefonDefteri.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TelefonDefteri.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TelefonDefteri.Web/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TelefonDefteriService;

namespace TelefonDefteri.Web.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {

            return View();
        }

        [Route("login")]
        [HttpPost]
        public IActionResult Login(string eMail, string password)
        {
            UserService userService = new UserService();

            var user = userService.Login(eMail, password);

            if (user != null && user.UserId != 0)
            {
                HttpContext.Session.SetString("user_email", user.Email);
                HttpContext.Session.SetString("user_name", user.Name);
                HttpContext.Session.SetString("user_lastName", user.LastName);
                HttpContext.Session.SetInt32("user_userId", user.UserId);


                return RedirectToAction("Index", "Home");
            }
            else
            {

                ViewBag.Message = string.Format("Hatalı Giriş");
                return RedirectToAction("Index", "Login");

            }
        }


        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Login");
        }


        [HttpGet]
        public IActionResult NewUser()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewUser(string name, string lastName, string eMail, string password)
        {
            UserService userService = new UserService();
            TelefonDefteriEntity.User user = new TelefonDefteriEntity.User()
            {
                Email = eMail,
                LastName = lastName,
                Password = password,
                Name = name
            };
            bool isSave = userService.InsertUser(user);

            if (isSave)
            {
                return RedirectToAction("Index", "Login");
            }

            return View();
        }

    }
}

TelefonDefteri.Web/Controllers/PhoneListController.cs
using Microsoft.AspNetCore.Mvc;
using TelefonDefteriEntity;
using TelefonDefteriService;

namespace TelefonDefteri.Web.Controllers
{
    public class PhoneListController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            PhoneListService phoneListService = new PhoneListService();
            var result = phoneListService.ListPeople();
            return View(result);
        }

        [HttpGet]
        public IActionResult NewList()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewList(string eMail, string lastName, string name, string address, string phone, string city, bool status)
        {
            PhoneListService pls = new();
            TelefonDefteriData.Models.PhoneList list = new()
            {
                Email = eMail,
                LastName = lastName,
                Name = name,
                Address = address,
                Phone = phone,
                City = city,
                Status = status
            };
            bool isSave = pls.ListAdd(list);

            if (isSave)
            {
                return RedirectToAction("Index", "PhoneList");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Update(int listId)
        {
            PhoneListService pls = new();

            var people = pls.GetPeople(listId);

            return View(people);
        }

        [HttpPost]
        public IActionResult UpdatePhoneList(string name, string lastName, string eMail, bool status, int listId)
        {
            PhoneListService pls = new();
            PhoneList list = new()
            {
                EMail = eMail,
                LastName = lastName,
                Status = status,
                Name = name,
                ListId = listId

            };
            bool isUpdate = pls.ListUpdate(list);

            if (isUpdate)
            {
                return Json("Kisi Güncellendi");

            }
            else
            {
                return Json("Kisi Güncellenemedi");
            }
        }

        [HttpPost]
        public IActionResult ListDelete(int id)
        {
            PhoneListService phoneListService = new();
            var result = phoneListService.ListDelete(id);
            return Json("Kisi Silindi");
        }
    }
}

TelefonDefteri.Web/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TelefonDefteriEntity;
using TelefonDefteriService;

namespace TelefonDefteri.Web.Controllers
{
    public class SettingsController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {

            return View();
        }

        [HttpPost]
        public IActionResult UpdateUser(string name, string lastName, string eMail, string password)
        {
            UserService userService = new UserService();
            User user = new User()
            {
                Email = eMail,
                LastName = lastName,
                Password = password,
                Name = name
            };
            bool isUpdate = userService.UpdateUser(user);

            if (isUpdate)
            {
                return Json("Kullanıcı Güncellendi");
            }
            else
            {
                return Json("Kullanıcı Güncellendi");
            }
        }
    }
}

TelefonDefteri.Web/Views/CallLog/Index.cshtml
<partial name="~/Views/Shared/_CallLogPartial.cshtml" />

TelefonDefteri.Web/Views/Home/Index.cshtml
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

TelefonDefteri.Web/Views/Login/Index.cshtml
@{ Layout = null;}
@model User
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdresDefteri</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    <div class="login-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-5">
                    <div class="login-wrap p-4 p-md-5">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="fa fa-user-o"></span>
                        </div>
                        <h3 class="text-center mb-4"><a href="~/Login/NewUser">Hesabın yok mu?</a></h3>

                        @using (Html.BeginForm("Login", "Login", FormMethod.Post, new {@id="loginForm"}))
                        {
                            <div class="form-group">
                                @Html.TextBoxFor(l => l.Email, new { @class = "form-control rounded-left ", placeholder = "E Mail", required = "required" })
                            </div>
                            <br />
                            <div class="form-group d-flex">

                                @Html.PasswordFor(m => m.Password, new { @class = "form-control rounded-left", placeholder = "Password", required = "required" })
                            </div>
                            <br />
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">
                                        <input type="checkbox" checked="">
                                        Remember Me
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="~/Login/ForgotPassword" id="btnForgotPassword" style="float:right">Forgot Password</a>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary rounded submit p-3 px-5 x-abs-center">Log In</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

TelefonDefteri.Web/Views/PhoneList/Index.cshtml
<partial name="~/Views/Shared/_PhoneListPartial.cshtml" />

TelefonDefteri.Web/Views/PhoneList/NewCallLog.cshtml
@model CallLog


<div class="list-update-text">
    <h4><span class="icon-list-update-text fa fa-pencil" style="color: #5d7892">Kişi Güncelleme</span></h4>
</div>

<div class="list-update col-md-6">

    @using (Html.BeginForm("AddCallLog", "CallLog", FormMethod.Post, new { @id = "addCallLog" }))
    {
        <div class="form-group">
            <div class="input-group">
            </div>
        </div>
        <div class="form-group ">
            <div class="input-group">
                @Html.TextBoxFor(l => l.CalledName, new { @class = "form-control", placeholder = "Name", name = "name" })
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                @Html.TextBoxFor(l => l.CalledLastName, new { @class = "form-control", placeholder = "LastName", name = "nameLast" })
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                @Html.TextBoxFor(l => l.CalledPhone, new { @class = "form-control", placeholder = "Email", name = "eMail" })
            </div>
        </div>
        <div class="form-group">
            <div class="input-group col-md-1">
                @Html.TextBoxFor(m => m.CallNext, new { @class = "form-control", placeholder = "Email", name = "status" })
            </div>
            @Html.HiddenFor(l => l.ListId)
        </div>
        <button type="button" class="updateRecord btn btn-primary">Kaydet</button>
        <button type="button" style="float:right" class="goBack btn btn-primary">Geri Dön</button>
    }
</div>

TelefonDefteri.Web/Views/PhoneList/NewList.cshtml
@model PhoneList

<div class="newListContainer col-md-6">

    @using (Html.BeginForm("NewList", "PhoneList", FormMethod.Post))
    {
        <div class="row">
            <div class="form-group col-md-6">
                <label for="inputAd">Ad</label>
                @Html.TextBoxFor(l => l.Name, new { @class = "form-control", id = "inputAd" })
            </div>
            <div class="form-group col-md-6">
                <label for="inputLastName">Soyad</label>
                @Html.TextBoxFor(l => l.LastName, new { @class = "form-control", id = "inputLastName" })
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail">Email</label>
            @Html.TextBoxFor(l => l.EMail, new { @class = "form-control", id = "inputEmail" })
        </div>
        <div class="form-group">
            <label for="inputAddress">Adres</label>
            @Html.TextBoxFor(l => l.Address, new { @class = "form-control", id = "inputAddress" })
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <label for="inputPhone">Telefon</label>
                @Html.TextBoxFor(l => l.Phone, new { @class = "form-control", id = "inputPhone" })
            </div>
            <div class="form-group col-md-4">
                <label for="inputCity">Şehir</label>
                @Html.TextBoxFor(l => l.City, new { @class = "form-control", id = "inputCity" })
            </div>
            <div class="form-group col-md-2">
                <label for="inputStatus">Durum</label>
                @Html.TextBoxFor(l => l.Status, new { @class = "form-control", id = "inputStatus", placeholder = "1 / 0" })
            </div>
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Kaydet</button>
            <button type="button" style="float:right" class="goBack btn btn-primary">Geri Dön</button>
        </div>
    }

</div>

TelefonDefteri.Web/Views/PhoneList/update.cshtml
@model PhoneList

<div class="list-update-text">
    <h4><span class="icon-list-update-text fa fa-pencil" style="color: #5d7892">Kişi Güncelleme</span></h4>
</div>

<div class="list-update col-md-6">

    @using (Html.BeginForm("UpdatePhoneList", "PhoneList", FormMethod.Post, new {@id="updatePhoneList" }))
    {
        <div class="form-group ">
            <div class="input-group">
                <span class="input-group-text">
                    <i class="fa fa-user text-primary"></i>
                </span>
                @Html.TextBoxFor(l => l.Name, new { @class = "form-control", placeholder = "Name", name = "name" })
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-text">
                    <i class="fa fa-user text-primary"></i>
                </span>
                @Html.TextBoxFor(l => l.LastName, new { @class = "form-control", placeholder = "LastName", name = "nameLast" })
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-text">
                    <i class="fa fa-envelope text-primary"></i>
                </span>
                @Html.TextBoxFor(l => l.EMail, new { @class = "form-control", placeholder = "Email", name = "eMail" })
            </div>
        </div>
        <div class="form-group">
            <div class="input-group col-md-1">
                <span class="input-group-text">
                    <i class="fa fa-edit text-primary"></i>
                </span>
                @Html.TextBoxFor(m => m.Status, new { @class = "form-control", placeholder = "Email", name = "status" })
            </div>
            @Html.HiddenFor(l => l.ListId)
        </div>
        <button type="button" class="updateRecord btn btn-primary">Kaydet</button>
        <button type="button" style="float:right" class="goBack btn btn-primary">Geri Dön</button>
    }
</div>

TelefonDefteri.Web/Views/Settings/Index.cshtml
<partial name="~/Views/Shared/_UpdateUserPartial.cshtml" />

TelefonDefteri.Web/Views/Shared/_CallLogPartial.cshtml
@model List<CallLog>

<br />
<a href="~/PhoneList/NewCallLog" class="btn btn-success btn-sm">Yeni Kayıt Oluştur</a>
<br />
<br />
<div class="callLogData">
    <table id="tbl1" class="callListTable table table-bordered" role="grid">
        <thead>
            <tr role="row">
                <th class="sorting" tabindex="0" aria-controls="tbl1" aria-sort="ascending" aria-label="artan sıralama"></th>
                <th class="sorting col-md-1" tabindex="0" aria-controls="tbl1" aria-sort="ascending" aria-label="Ad">Ad</th>
                <th class="sorting col" tabindex="0" aria-controls="tbl1" aria-sort="ascending" aria-label="Soyad">Soyad</th>
                <th class="sorting" tabindex="0" aria-controls="tbl1" aria-sort="ascending" aria-label="Telefon">Telefon</th>

            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @foreach (var item in Model)
                {
                    <tr role="row" data-id="@item.ListId">
                        <td class="subList text-center">
                            <span id="btnDetail" class="btn btn-info btn-sm open" data-show="false"><i class="fa fa-plus"></i></span>
                        </td>
                        <td>@item.CalledName</td>
                        <td>@item.CalledLastName</td>
                        <td>@item.CalledPhone</td>
                    </tr>
                    <tr class="clTableDetail" style="display:none">
                        <td></td>
                        <td colspan="7">
                            <div>
                                <table id="table-detail" class="table table-bordered table-sm table-striped table-light">
                                    <thead>
                                        <tr role="row">
                                            <th>Tarih</th>
                                            <th>Arama Durumu</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

TelefonDefteri.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdresDefteri</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
            <div class="custom-menu">
                <button type="button" id="sidebarCollapse" class="btn btn-primary">
                    <i class="fa fa-bars"></i>
                    <span class="sr-only">Toggle Menu</span>
                </button>
            </div>
            <div class="p-4">
                <h1><a href="index" class="logo">Adres Defteri <span>Aramalarını Düzenle</span></a></h1>
                <div class="welcome">Hoşgeldin @Context.Session.GetString("user_name") @Context.Session.GetString("user_lastName") </div>
                <ul class="list-unstyled components mb-5">
                    <li>
                        <a href="~/home/index" style="margin-top:100px"><span class="fa fa-home mr-3"></span> Anasayfa</a>
                    </li>
                    <li>
                        <a href="~/phoneList/index"><span class="fa fa-user mr-3"></span> Kişi Listesi</a>
                    </li>
                    <li>
                        <a href="~/callLog/index"><span class="fa fa-briefcase mr-3"></span> Arama Kaydı</a>
                    </li>
                    <li>
                        <a href="~/settings/index"><span class="fa fa-cogs mr-3"></span> Kullanıcı Ayarları</a>
                    </li>
                    <li>
                        <a asp-controller="login" asp-action="logout"><span class="fa fa-sign-out mr-3"></span> Log Out</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="context" style="width:100%">

            @RenderBody()

        </div>
    </div>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.2/dist/sweetalert2.all.min.js"></script>
    <script src="https://use.fontawesome.com/bfd989aaaf.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js"></script>
</body>
</html>

TelefonDefteri.Web/Views/Shared/_PhoneListPartial.cshtml
@model List<PhoneList>

<br />
<a href="~/PhoneList/NewList" class="btn btn-success btn-sm">Yeni Kişi Oluştur</a>
<br />
<br />
<div class="list-table col-md-10">
    <table class="phoneListTable table table-bordered">
        <thead>
            <tr role="row">
                <th class="sorting" tabindex="0" aria-controls="tbl1" aria-sort="ascending" aria-label="Ad">Ad</th>
                <th class="sorting" tabindex="0" aria-controls="tbl1" aria-sort="ascending" aria-label="Soyad">Soyad</th>
                <th class="sorting" tabindex="0" aria-controls="tbl1" aria-sort="ascending" aria-label="EMail">E Mail</th>
                <th class="sorting" tabindex="0" aria-controls="tbl1" aria-sort="ascending" aria-label="Durum">Durum</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @foreach (var item in Model)
                {
                    <tr role="row">
                        <td>@item.Name</td>
                        <td>@item.LastName</td>
                        <td>@item.EMail</td>
                        <td style="text-align:center">@item.Status</td>
                        <td style="text-align:center"> <input type="button" class="btn btn-success btn-sm purple" value="Güncelle" onclick="@("window.location.href='" + @Url.Action("Update", "PhoneList", new {listId =item.ListId })  + "'");" /></td>
                        <td style="text-align:center"><button type="button" data-model-id="@item.ListId" class="deleteRecord btn btn-danger btn-sm black"><i class="fa fa-trash-o"></i>Sil</button></td>
                    </tr>
                }}
        </tbody>
    </table>
</div>

TelefonDefteri.Web/Views/Shared/_UpdateUserPartial.cshtml
@model User
@using Microsoft.AspNetCore.Http
<div class="update-container">
    <div class="update-header">
        <h4><span class="icon-update-header fa fa-pencil" style="color: #5d7892">Kullanıcı Güncelleme</span></h4>
    </div>
    <br />
    <br />
    <div class="update-box">
        @using (Html.BeginForm("UpdateUser", "Settings", FormMethod.Post, new { @id = "updateUser" }))
        {
            <div class="row">
                <div class="update-form-row">
                    <div class="col-12 col-xl-6 col-lg-8">
                        <div class="input-group">
                            <span class="input-group-text">
                                <i class="fa fa-user text-primary"></i>
                            </span>
                            @Html.TextBoxFor(n => n.Name, new { @class = "form-control", placeholder = @Context.Session.GetString("user_name") })
                        </div>
                    </div>
                </div>
                <div class="update-form-row">
                    <div class="col-12 col-xl-6 col-lg-8">
                        <div class="input-group">
                            <span class="input-group-text">
                                <i class="fa fa-user text-primary"></i>
                            </span>
                            @Html.TextBoxFor(n => n.LastName, new { @class = "form-control", placeholder = @Context.Session.GetString("user_lastName") })
                        </div>
                    </div>
                </div>
                <div class="update-form-row">
                    <div class="col-12 col-xl-6 col-lg-8">
                        <div class="input-group">
                            <span class="input-group-text">
                                <i class="fa fa-envelope text-primary"></i>
                            </span>
                            @Html.TextBoxFor(n => n.Email, new { @class = "form-control", placeholder = @Context.Session.GetString("user_email") })
                        </div>
                    </div>
                </div>
                <div class="update-form-row">
                    <div class="col-12 col-xl-6 col-lg-8">
                        <div class="input-group">
                            <span class="input-group-text">
                                <i class="fa fa-lock text-primary"></i>
                            </span>
                            @Html.PasswordFor(n => n.Password, new { @class = "form-control", placeholder = "Password" })
                        </div>
                        @Html.HiddenFor(l => l.UserId)
                    </div>
                </div>
                <div class="col-12 col-lg-9 ml-auto">
                    <button class="updateUserRecord btn btn-primary" type="button">Kaydet</button>
                </div>
            </div>
        }
    </div>
</div>